# Generated by Django 6.0.7 on 2026-09-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='medical_record_attachments/'),
        ),
    ]
