# Generated by Django 6.0.7 on 2026-09-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratoryrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Requested'), ('sample_collected', 'Sample Collected'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
