# Generated by Django 6.0.7 on 2026-09-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_alter_laboratoryrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratoryresult',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='laboratory_reports/'),
        ),
    ]
