# Generated by Django 6.0.7 on 2026-09-14 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0003_laboratoryresult_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratoryrequest',
            name='laboratory_technician',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'lab_technician'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_laboratory_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
