# Generated by Django 6.0.7 on 2026-09-12 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_remove_department_created_at_and_more'),
        ('doctors', '0002_doctor_availability_doctor_consultation_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_department', to='doctors.doctor'),
        ),
    ]
