# Generated by Django 6.0.7 on 2026-09-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_provider',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
