# Generated by Django 6.0.7 on 2026-09-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_availability_doctor_consultation_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='license_file',
            field=models.FileField(blank=True, null=True, upload_to='doctor_licenses/'),
        ),
    ]
